services:
  mysql:
    image: mysql
    container_name: mysql_container
    ports:
      - 5050:3306
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_DATABASE: mydatabase
