services:
  postgres:
    image: postgres
    container_name: postgres_container
    ports:
      - 5050:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: dep_takas
